### PR TITLE
Upmerge 2021 07 26

### PR DESCRIPTION
**Pull request by mbolivar-nordic**

### CODE REVIEW

**Review by de-nordic — APPROVED** [review]
I have looked at and tested the mcuboot serial recovery, on nrf52840dk as a test platform.
Everything seems to be OK.
Looks OK.

**Comment by de-nordic** [comment]
@mbolivar-nordic Do you know what is the problem with compliance?

**Comment by mbolivar-nordic** [comment]
```
IsADirectoryError: [Errno 21] Is a directory: '/home/work/bootloader/mcuboot/ext/cddl-gen'
```

No clue

**Comment by mbolivar-nordic** [comment]
I can reproduce locally; investigating

**Comment by mbolivar-nordic** [comment]
> I can reproduce locally; investigating

I rebooted and lost the Python command to reproduce from my shell history, and now I can't log in to CI for some reason. So now I'm blocked until that's resolved unless someone can PM me the CI compliance command from the console output.

**Comment by mbolivar-nordic** [comment]
> @mbolivar-nordic Do you know what is the problem with compliance?

https://github.com/zephyrproject-rtos/zephyr/pull/37451 should fix it

**Review by nvlsianpu — APPROVED** [review]

**Comment by sigvartmh** [comment]
Can https://github.com/mcu-tools/mcuboot/commit/e933e586ec179789d98d10821226533586577460 be included in the up-merge.

**Comment by mbolivar-nordic** [comment]
> Can [mcu-tools/mcuboot@e933e58](https://github.com/mcu-tools/mcuboot/commit/e933e586ec179789d98d10821226533586577460) be included in the up-merge.

I need @nvlsianpu to approve that at this point. We are several weeks in and I'm trying to slow down new patches unless they fix an issue with the current upmerge.

**Comment by nvlsianpu** [comment]
I'm ok with adding https://github.com/mcu-tools/mcuboot/commit/e933e586ec179789d98d10821226533586577460 here

**Review by nvlsianpu — CHANGES_REQUESTED** [review]
We have cbor encode issue which cause bad integer encoding so some values can be encoded on byte length which is not power of 2.
for instance 0x010144 was encoded as `19 01 01 44`, but should be as `1a 00 01 01 44`

**Comment by nvlsianpu** [comment]
^^
https://github.com/mcu-tools/mcuboot/pull/1105 is fix for that.

**Review by nvlsianpu — APPROVED** [review]

**Comment by mbolivar-nordic** [comment]
> I'm ok with adding [mcu-tools/mcuboot@e933e58](https://github.com/mcu-tools/mcuboot/commit/e933e586ec179789d98d10821226533586577460) here

Added and restarted cI.

**Comment by mbolivar-nordic** [comment]
I had to force push this. See https://github.com/nrfconnect/sdk-nrf/pull/5068#issuecomment-902761237 for details.

**Pull request merged**
