### PR TITLE
[nrf fromlist] zephyr: Fix support for single application with ...

### PR DESCRIPTION
**Pull request by de-nordic**
... serial recovery

The commit fixes compilation error when attempting to build
support for single application slot with serial recovery enabled.

Upstream PR: https://github.com/mcu-tools/mcuboot/pull/1163

Signed-off-by: Dominik Ermel <dominik.ermel@nordicsemi.no>

### CODE REVIEW

**Comment by de-nordic** [comment]
@MarekPieta @emob-nordic Could you please review upstream too?

**Review by MarekPieta — APPROVED** [review]

**Comment by MarekPieta** [comment]
Thank you for the fix

**Review by pdunaj — APPROVED** [review]

**Review by emob-nordic — APPROVED** [review]

**Comment by emob-nordic** [comment]
> @MarekPieta @emob-nordic Could you please review upstream too?

I can but it doesn't count :(

**Review by nvlsianpu — APPROVED** [review]

**Comment by de-nordic** [comment]
> 
> 
> Should we add a known issue?

@pdunaj I am not sure how to address it. I would rather have it merged in fixed in 1.7.

**Comment by pdunaj** [comment]
> I am not sure how to address it

If I am correct we can always edit `doc/nrf/known_issues.rst`. Entry can be added there with `v1.7.0` which mean problem is visible in this version. @shantha-14 , am I right?

**Comment by pdunaj** [comment]
Hi @carlescufi , we need to merge it asap. The mcuboot does not build correctly without it and it seems this PR went unnoticed.

**Pull request merged**
