### PR TITLE
Ncs 1.8 rebase

### PR DESCRIPTION
**Pull request by mbolivar-nordic**
Empty diff with v1.7.99-ncs4-rc1, but this is just a starting out point. I need help from @nvlsianpu  to finish the job, as there are a couple of problems that I do not know how to solve.

Here is a checklist:

- [x] Thingy:53 support has two problems I can see:
     - [x] `zephyr: Removed old external flash configs for Thingy53.` should have been sent upstream, for reasons explained in https://github.com/mcu-tools/mcuboot/pull/1122#issuecomment-983113089. I have changed this to `toup` here for now and put it next to the `fromlist` patch adding support for thingy:53. cc @MarekPieta @osaether 
     - [x] `boot: zephyr: Remove CONFIG_USB from Thingy53 configuration` should have been sent upstream as well. This is already a `toup` in our main branch, even though we are not supposed to be using that tag anymore. This was introduced in the most recent upmerge: https://github.com/nrfconnect/sdk-mcuboot/pull/180 cc @rlubos 
 - [x] The `kconfig: reduce downstream patch` patch requests a squash that doesn't apply. The commit log (see https://github.com/nrfconnect/sdk-mcuboot/commit/595fb49314be2672fdcf040475265929e24ef457 where it was cherry-picked from) seems to indicate that it needs some more splitting up and squashing, but I don't understand the request. cc @hakonfam

### CODE REVIEW

**Comment by nvlsianpu** [comment]
>  The kconfig: reduce downstream patch patch requests a squash that doesn't apply. The commit log (see 595fb49 where it was cherry-picked from) seems to indicate that it needs some more splitting up and squashing, but I don't understand the request. cc @hakonfam

drop commits listed in commit message. Only keep the one with `squash!` in the title.
The only remaining patch should be the sourcing of the Kconfig file in the mcuboot module in the nrf repo.: lines 11 and 12.
I think only way to do so is interactive rebase.

**Comment by nvlsianpu** [comment]
`zephyr: Removed old external flash configs for Thingy53. is sent upstream` https://github.com/mcu-tools/mcuboot/pull/1230

**Comment by nvlsianpu** [comment]
@mbolivar-nordic I did branch where I believe I did resolved above listed issues: https://github.com/nvlsianpu/fw-nrfconnect-mcuboot/tree/anpu-ncs-1.8-rebase

**Comment by nvlsianpu** [comment]
[nrf fromtree] boot_serial: cleanup max output size calculation: is fromlist at the moment.

**Comment by mbolivar-nordic** [comment]
Thanks @nvlsianpu --- so is this OK then?

**Comment by nvlsianpu** [comment]
> Thanks @nvlsianpu --- so is this OK then?

It is not.

**Review by nvlsianpu — APPROVED** [review]

**Review by hakonfam — APPROVED** [review]
Thanks for handling the kconfig @nvlsianpu 👍🏻

**Comment by nvlsianpu** [comment]
@mbolivar-nordic I corrected [nrf fromtree] to [nrf fromlist] in the last commit.

**Comment by nvlsianpu** [comment]
Just found that below Kconfig shouldn't be removed in commit
`[nrf noup] treewide: add NCS partition manager support`
and shouldn't be added by `[nrf fromtree] zephyr/boot_serial_extension: kconfig of custom command for get images status`

```
menuconfig ENABLE_MGMT_PERUSER
	bool "Enable system specific mcumgr commands"
	depends on BOOT_SERIAL_UART
	help
	  The option enables processing of system specific mcumgr commands;
	  system specific commands are within group MGMT_GROUP_ID_PERUSER (64)
	  and above, as defined within mcumgr library.
	  These are system specific command and system specific implementation
	  function is required to process these commands.
```

**Comment by nvlsianpu** [comment]
^^ @mbolivar-nordic I did another rebase for fix that on my branch https://github.com/nvlsianpu/fw-nrfconnect-mcuboot/tree/anpu-ncs-1.8-rebase

**Pull request merged**
