### PR TITLE
[nrf fromlist] bootutil: loader: Add post copy hook to swap function

### PR DESCRIPTION
**Pull request by sigvartmh**
Currently the post copy hook is only called from the `copy_region` function. However when another update method than `BOOT_UPGRADE_ONLY` is selected this function is not called. This adds post copy hook to the end of `boot_swap_image` when we know the swap is complete.

Ref. NCSDK-16932

Signed-off-by: Sigvart Hovland <sigvart.hovland@nordicsemi.no>

### CODE REVIEW

**Review by tejlmand — CHANGES_REQUESTED** [review]
a `[nrf fromlist]` commit message must contain a link to upstream PR.

**Review by nvlsianpu — COMMENTED** [review]
The patch LGTM
I don't see the upstream PR

**Comment by sigvartmh** [comment]
Upstream PR: https://github.com/mcu-tools/mcuboot/pull/1476  sorry was a bit too fast.

**Review by nvlsianpu — APPROVED** [review]

**Comment by nvlsianpu** [comment]
@sigvartmh Can you make this fromtree? The upstream PR was merged.

**Comment by sigvartmh** [comment]
Ah sorry didn't see this before now. Will do

**Pull request closed without merging**
