### PR TITLE
[nrf noup] workflows: Add a backport workflow

### PR DESCRIPTION
**Pull request by rlubos**
Enable backporting of PRs.

### CODE REVIEW

**Comment by rlubos** [comment]
@de-nordic @nvlsianpu Please let me know what you think about this, that way you could create backport PRs automatically just like in other repos.

**Comment by de-nordic** [comment]
> @de-nordic @nvlsianpu Please let me know what you think about this, that way you could create backport PRs automatically just like in other repos.

This will only start backporting issue once the fix is merged?

**Comment by rlubos** [comment]
> > @de-nordic @nvlsianpu Please let me know what you think about this, that way you could create backport PRs automatically just like in other repos.
> 
> This will only start backporting issue once the fix is merged?

Yes, the backport PR is created after the PR towards `main` is merged.

**Comment by de-nordic** [comment]
> 
> Yes, the backport PR is created after the PR towards `main` is merged.

How does it know where to backport?

**Comment by rlubos** [comment]
> > Yes, the backport PR is created after the PR towards `main` is merged.
> 
> How does it know where to backport?

We create `backport-v2.1.0-ncs2-branch` label, contributors add this label to their PRs. The bot extracts the destination branch name from the label.

**Review by de-nordic — APPROVED** [review]

**Pull request merged**
