### PR TITLE
Clarify the purpose of the "mcuboot_pad" partition

### PR DESCRIPTION
**Pull request by vidarbe**
Signed-off-by: Vidar Berg <vidar.berg@nordicsemi.no>

### CODE REVIEW

**Review by nvlsianpu — CHANGES_REQUESTED** [review]
Pleas add [nrf noup] sauce tag in the commit message.
Message ought contain message body as well.

**Comment by nvlsianpu** [comment]
should be [nrf noup], lower case only

**Comment by vidarbe** [comment]
@nvlsianpu , sorry, I hope it's ok now.

**Review by nvlsianpu — APPROVED** [review]

**Review by hakonfam — APPROVED** [review]

**Comment by nvlsianpu** [comment]
@vidarbe Do you expected to change `nrf` manifest reference to sdk-mcuboot while someone else do another PR here?

**Comment by vidarbe** [comment]
Yes, I think it can wait til someome else makes a new PR here.

**Pull request merged**
