### PR TITLE
Upmerge to Zephyr fork of MCUboot at 143485e35b8da7d234677d8920a28f5ea03f6d09

### PR DESCRIPTION
**Pull request by de-nordic**

### CODE REVIEW

**Comment by mbolivar-nordic** [comment]
> @SebastianBoe @sigvartmh Please take careful look at [4c1749e](https://github.com/nrfconnect/sdk-mcuboot/commit/4c1749e0af95a4ba88113838d4287e96173ddf55) 

@de-nordic something went wrong here; was this manually generated or done by the bot? I'm assuming it was done manually since the committer email is yours and not the bot's. This `#if` is unterminated in boot/bootutil/src/image_ec256.c, leading to build failures:

```
+#if defined(MCUBOOT_USE_TINYCRYPT) || defined(MCUBOOT_USE_CC310) || \
+    defined(MCUBOOT_USE_MBED_TLS) || defined (MCUBOOT_USE_NRF_EXTERNAL_CRYPTO)
```

and this new version of the patch is mentioning things about Cypress (`+/*TODO: remove this after cypress port mbedtls to abstract crypto api */`) that doesn't appear in the original patch which is being reverted (972ab61549ac45ee680c71f943fe88e9ca5a7bda).

**Comment by SebastianBoe** [comment]
> @SebastianBoe @sigvartmh Please take careful look at [4c1749e](https://github.com/nrfconnect/sdk-mcuboot/commit/4c1749e0af95a4ba88113838d4287e96173ddf55) and [4c3e5e1](https://github.com/nrfconnect/sdk-mcuboot/commit/4c3e5e1f3381f5814dc523a168cebef5685ffb6d). Thanks!

Hi, I'm not sure If I have time to do so unfortunately.

**Review by sigvartmh — COMMENTED** [review]
~CC310 seems to be broken in this upmerge not really sure why. I'm currently looking into it.~

This was fixed by @de-nordic  Thank you :)

**Comment by de-nordic** [comment]
> ~CC310 seems to be broken in this upmerge not really sure why. I'm currently looking into it.~
> 
> This was fixed by @de-nordic Thank you :)

@sigvartmh can you check whether I have covered all problems?

**Comment by frkv** [comment]
Bisectability-issue:

It seems  flash_area_get_sector was [added](https://github.com/nrfconnect/sdk-mcuboot/pull/246/commits/c89a94f120763265a0859ae6645b159be16b826d) in a commit that came after first [usage](https://github.com/nrfconnect/sdk-mcuboot/pull/246/commits/68dcc0ee10317096d164dadd2623a3a0be4352bb)

**Review by frkv — APPROVED** [review]
LGTM pending passing tests

**Pull request merged**
