### PR TITLE
[nrf noup] ci: replace jenkins pipeline in jenkinsfile with a stub

### PR DESCRIPTION
**Pull request by thst-nordic**
load pipeline from internal config repo

Signed-off-by: Thomas Stilwell <Thomas.Stilwell@nordicsemi.no>

### CODE REVIEW

**Comment by jfischer-no** [comment]
cherry-picked to  #136

**Review by jfischer-no — APPROVED** [review]

**Comment by thst-nordic** [comment]
I'm guessing since the upmerge just started it is going to be a few days.  
 
since this is only 1 [noup] commit, can we merge it to master so compliance works on other PR's?

@carlescufi

**Review by carlescufi — APPROVED** [review]

**Comment by nvlsianpu** [comment]
@thst-nordic This patch removes patch which allows to skip part of test for [nrf merge] up sauce code.
Can this be introduced back?

**Comment by thst-nordic** [comment]
I'll take a look

**Pull request merged**
