### PR TITLE
mcuboot: Don't create second image partition in single slot build

### PR DESCRIPTION
**Pull request by sebastiandraus**
This commit sets size of second image partition to zero if CONFIG_SINGLE_APPLICATION_SLOT=y, hence the secondary image partition is dropped by partition manager. This allows to use available flash to have bigger slot image without unnecessary workarounds.

Tested with Zigbee samples, mcuboot main() extended to print size and offset of the slot_0 after startup:
`printk("image_0 offset: 0x%x\n", FLASH_AREA_OFFSET(image_0));`
`printk("image_0 size:   0x%x\n", FLASH_AREA_SIZE(image_0));`

Zigbee sample built with:
`west build -b nrf52840dk_nrf52840 --pristine -s ~/GIT/ncs/nrf/samples/zigbee/light_switch -- -Dmcuboot_OVERLAY_CONFIG="usb_cdc_acm_log_recovery.conf single_slot.conf" -DCONFIG_BOOTLOADER_MCUBOOT=y -DPM_STATIC_YML_FILE=/home/sedr/GIT/ncs/nrf/samples/zigbee/ncp/configuration/nrf52840dk_nrf52840/pm_static.yml`
, pm_static.yml used to increase mcuboot partition size:
```
 mcuboot:
   address: 0x0
   end_address: 0x10000
   region: flash_primary
   size: 0x10000
```

mcuboot flashed to nrf52840 board, reported correct image_0 size and offset (compared with partitions.yaml):
```
*** Booting Zephyr OS build v2.4.0-ncs1-3484-g21046b8cdb4e  ***
I: Starting bootloader
image_0 offset: 0x10000
image_0 size:   0xe1000
I: Enter the serial recovery mode
I: Device suspended
I: Device resumed
I: from suspend
```
Zigbee light switch image app_update.bin uploaded with mcumgr, booted corectly after reset.
`./mcumgr -t 5 --conntype serial --connstring=/dev/ttyACM2 image upload  ~/GIT/ncs/nrf/build/zephyr/app_update.bin`

2nd image upload tested with different Zigbee sample:
`west build -b nrf52840dk_nrf52840 --pristine -s ~/GIT/ncs/nrf/samples/zigbee/light_bulb -- -Dmcuboot_OVERLAY_CONFIG="usb_cdc_acm_log_recovery.conf single_slot.conf" -DCONFIG_BOOTLOADER_MCUBOOT=y -DPM_STATIC_YML_FILE=/home/sedr/GIT/ncs/nrf/samples/zigbee/ncp/configuration/nrf52840dk_nrf52840/pm_static.yml`

Board reset with button_0 pressed to enter recovery, new image uploaded with mcumgr. After reset, sample booted correctly.

### CODE REVIEW

**Review by de-nordic — APPROVED** [review]
Looks OK.

**Review by hakonfam — APPROVED** [review]
LGTM, would it be helpful with a comment in the pm.yml explaning why we set it to 0 when 'SINGLE_APPLICATION_SLOT` is set, or do we consider the reference to the kconfig enough information?

Also, would it be more clear if the whole mcuboot_secondary declaration was inside an `#ifdef` ? We don't need any of the other information when the size is 0 and it is dropped from the solution entirely.

**Comment by sebastiandraus** [comment]
@hakonfam It's probably better to `#ifdef` sholw mcuboot_secondary, I'll change it and comment it

**Review by de-nordic — CHANGES_REQUESTED** [review]
One note: this should be [nrf noup]

**Review by de-nordic — APPROVED** [review]

**Review by nvlsianpu — APPROVED** [review]

**Comment by nvlsianpu** [comment]
@sebastiandraus Please open manifest update PR to the `nrf`.

**Comment by sebastiandraus** [comment]
PR with manifest update opened in nrf repo: https://github.com/nrfconnect/sdk-nrf/pull/3832

**Pull request merged**
