### PR TITLE
[nrf noup] crypto: ecdsa: Fix shared crypto NSIB and MCUBoot with EXT_ABI

### PR DESCRIPTION
**Pull request by sigvartmh**
After the upmerge using external crypto from NSIB in MCUBoot resulted in build failures. This commit fixes the build failures.

Ref. NCSDK-23994

### CODE REVIEW

**Review by de-nordic — CHANGES_REQUESTED** [review]
The tag is missing from title.

**Comment by nordicjm** [comment]
How is this actually used? If I configure a project for nrf9160dk with mcuboot and b0 then set mcuboot to use the shared crypto function from the bootloader I get a bunch of linker errors:
```
/opt/zephyr-sdk-0.16.3/arm-zephyr-eabi/bin/../lib/gcc/arm-zephyr-eabi/12.2.0/../../../../arm-zephyr-eabi/bin/ld.bfd: app/libapp.a(image_validate.c.obj): in function `bootutil_sha256_init':
/tmp/bb/bootloader/mcuboot/boot/bootutil/include/bootutil/crypto/sha256.h:200: undefined reference to `bl_sha256_init'
/opt/zephyr-sdk-0.16.3/arm-zephyr-eabi/bin/../lib/gcc/arm-zephyr-eabi/12.2.0/../../../../arm-zephyr-eabi/bin/ld.bfd: app/libapp.a(image_validate.c.obj): in function `bootutil_sha256_update':
/tmp/bb/bootloader/mcuboot/boot/bootutil/include/bootutil/crypto/sha256.h:212: undefined reference to `bl_sha256_update'
/opt/zephyr-sdk-0.16.3/arm-zephyr-eabi/bin/../lib/gcc/arm-zephyr-eabi/12.2.0/../../../../arm-zephyr-eabi/bin/ld.bfd: app/libapp.a(image_validate.c.obj): in function `bootutil_sha256_finish':
/tmp/bb/bootloader/mcuboot/boot/bootutil/include/bootutil/crypto/sha256.h:218: undefined reference to `bl_sha256_finalize'
/opt/zephyr-sdk-0.16.3/arm-zephyr-eabi/bin/../lib/gcc/arm-zephyr-eabi/12.2.0/../../../../arm-zephyr-eabi/bin/ld.bfd: app/libapp.a(image_validate.c.obj): in function `bootutil_sha256_update':
/tmp/bb/bootloader/mcuboot/boot/bootutil/include/bootutil/crypto/sha256.h:212: undefined reference to `bl_sha256_update'
/opt/zephyr-sdk-0.16.3/arm-zephyr-eabi/bin/../lib/gcc/arm-zephyr-eabi/12.2.0/../../../../arm-zephyr-eabi/bin/ld.bfd: app/libapp.a(image_validate.c.obj): in function `bootutil_sha256_init':
/tmp/bb/bootloader/mcuboot/boot/bootutil/include/bootutil/crypto/sha256.h:200: undefined reference to `bl_sha256_init'
/opt/zephyr-sdk-0.16.3/arm-zephyr-eabi/bin/../lib/gcc/arm-zephyr-eabi/12.2.0/../../../../arm-zephyr-eabi/bin/ld.bfd: app/libapp.a(image_validate.c.obj): in function `bootutil_sha256_update':
/tmp/bb/bootloader/mcuboot/boot/bootutil/include/bootutil/crypto/sha256.h:212: undefined reference to `bl_sha256_update'
/opt/zephyr-sdk-0.16.3/arm-zephyr-eabi/bin/../lib/gcc/arm-zephyr-eabi/12.2.0/../../../../arm-zephyr-eabi/bin/ld.bfd: app/libapp.a(image_validate.c.obj): in function `bootutil_sha256_finish':
/tmp/bb/bootloader/mcuboot/boot/bootutil/include/bootutil/crypto/sha256.h:218: undefined reference to `bl_sha256_finalize'
/opt/zephyr-sdk-0.16.3/arm-zephyr-eabi/bin/../lib/gcc/arm-zephyr-eabi/12.2.0/../../../../arm-zephyr-eabi/bin/ld.bfd: app/libapp.a(image_ecdsa.c.obj): in function `bootutil_ecdsa_verify':
```

**Comment by sigvartmh** [comment]
@de-nordic Tag fixed

**Review by de-nordic — APPROVED** [review]

**Comment by sigvartmh** [comment]
Is the CI for this just broken or?

**Comment by de-nordic** [comment]
> Is the CI for this just broken or?

Yes and or.

**Review by hakonfam — APPROVED** [review]

**Comment by nordicjm** [comment]
@sigvartmh I think we need a chat some time for this, whilst trying to get TF-M working with sysbuild I'm finding this system to be pretty much broken, applying `external_crypto.conf` to mcuboot causes it to fail to boot because it tries to forward crypto and gets an error (and I can't really see why mcuboot would forward that at all, doesn't really make any sense? b0 provides it, so the app should be using the b0 calls, why would it use it via mcuboot which would use it via b0?)

**Comment by sigvartmh** [comment]
@nordicjm Sure we can have it on Monday if you have time. Not sure if forwarding is enabled by default, the general idea when it was implemented is that you can forward the crypto all the way up to the application. In reality, this does not work for TrustZone-enabled devices as you would only reach up to the secure part of the application, and calling it from the app would result in a secure fault.

All this was done in an attempt to create a system that would save the amount of crypto you would initially need in your application. However, as cryptography evolves you may need to use more secure crypto operations which B0 does not provide.. It was maybe an ambitious project and maybe we should discuss if it's time to deprecate this as I haven't heard of anyone using it.

**Review by nordicjm — APPROVED** [review]

**Pull request merged**
