### PR TITLE
Thingy:53 board configuration to noup

### PR DESCRIPTION
**Pull request by kapi-no**

### CODE REVIEW

**Comment by nordicjm** [comment]
Looks like these are empty commits? Or at least github shows no changes

**Comment by nordicjm** [comment]
*Commit is being added then removed

**Comment by kapi-no** [comment]
@nordicjm, yes, that's my intention. One commit comes from the upstream where the configuration file has been removed and the other should remain downstream where the configuration file will now be hosted.

This PR should ease the next upmerge efforts as everything will be set up to work for Thingy:53 in NCS. The [fromtree] commit will be deleted by the original commit and the [noup] commit should remain after upmerge rebase process.

**Review by de-nordic — APPROVED** [review]
Does not seem to break anything :)

**Review by nvlsianpu — APPROVED** [review]

**Comment by kapi-no** [comment]
@nordicjm , could you approve?

**Review by nordicjm — APPROVED** [review]

**Pull request merged**
