### PR TITLE
[nrf noup] boards: thingy53: disable GPIO ISR support

### PR DESCRIPTION
**Pull request by nika-nordic**
Change disables GPIO interrupt support in Zephyr GPIO driver, which is not obligatory for MCUboot.
This is needed to reduce memory footprint.

### CODE REVIEW

**Comment by nika-nordic** [comment]
CI is red but the failures seem to be unrelated to the changes from this PR

**Review by anangl — APPROVED** [review]

**Review by kapi-no — APPROVED** [review]

**Comment by kapi-no** [comment]
@de-nordic or @nordicjm can you take a look to see if the GPIO interrupt mode isn't needed for the MCUboot image in the Thingy:53 configuration?

(MCUboot image for Thingy:53 builds correctly in the Twistter CI)

**Comment by de-nordic** [comment]
I have built the Machine Learning application with this PR and it seems that MCUboot serial recovery works ok, and can be triggered while holding the Button1 while resetting device.

**Review by nordicjm — APPROVED** [review]

**Comment by nordicjm** [comment]
MCUboot does not use GPIO interrupts, it just monitors the pin at startup, would be good to have this enabled when compiling MCUboot for any nordic device...

**Review by de-nordic — APPROVED** [review]

**Pull request merged**
