### PR TITLE
fixup! [nrf noup] boot: add 'minimal' configuration files

### PR DESCRIPTION
**Pull request by sigvartmh**
Removed 
```
CONFIG_REBOOT=n
CONFIG_RESET_ON_FATAL_ERROR=n
```

People using this file as a reference for their release mode will potentially set their bootloader in a spin lock until an external reset triggers the device. Like a power/reset line, which only some products potentially have.

There have apparently been customer cases which have been reported where this is the case.

Ref. NCSDK-19789

### CODE REVIEW

**Review by de-nordic — APPROVED** [review]

**Review by nordicjm — APPROVED** [review]

**Comment by nordicjm** [comment]
If you want this in for the 2.3 release, speak with Shantha

**Comment by sigvartmh** [comment]
Not needed for 2.3 👍  Thanks for the review.

**Review by mbolivar-nordic — CHANGES_REQUESTED** [review]
please fix your commit message

**Comment by sigvartmh** [comment]
Should be fixed now I misunderstood the instructions in confluence.

**Review by mbolivar-nordic — APPROVED** [review]

**Comment by de-nordic** [comment]
@sigvartmh Rebase will be needed.

**Comment by de-nordic** [comment]
I have marked this DNM, because It has been already taken in as part of upmerge (https://github.com/jfischer-no/sdk-nrf/tree/upmerge-06032023), within sdk-mcuboot at this commit https://github.com/nrfconnect/sdk-mcuboot/commit/7e71bc4842258fb2e684dd5444f8d889595b18d3.

**Comment by sigvartmh** [comment]
Included in the upmerge when it comes.

**Pull request closed without merging**
