### PR TITLE
bootutil: loader.c: Fix network core update external flash with 1 image

### PR DESCRIPTION
**Pull request by sigvartmh**
Using sequential updates on the nRF53 with external flash would cause network core updates to fail. This is because the update would be located in the external flash which is network core cannot access. This fixes the issue by copying the data from the external flash into RAM of the application core which can be read by the network core.

This commit also contains some minor renaming to align with the naming scheme used in the `loader.c` file for flash areas.

Ref: NCSDK-21379

### CODE REVIEW

**Review by osaether — APPROVED** [review]
I tried it locally and the PR fixes the issue.

**Comment by de-nordic** [comment]
@sigvartmh You want this in ncs 2.4?

**Review by hakonfam — APPROVED** [review]

**Comment by de-nordic** [comment]
@sigvartmh @hakonfam Is this targeting NCS 2.4?

**Comment by sigvartmh** [comment]
Yes. I wasn't sure if I should add the milestone or not. Added it now.

**Review by de-nordic — APPROVED** [review]

**Comment by de-nordic** [comment]
> @de-nordic Yes. I wanted to know if I should add the milestone or not. Just so you know – I added it now.

You can always add the milestone, if you consider fix to be needed. The milestone can be removed by people responsible for release.

**Review by nvlsianpu — APPROVED** [review]

**Pull request merged**
