### PR TITLE
DNM [nrf mergeup] Upmerge 180121

### PR DESCRIPTION
**Pull request by jfischer-no**
Upmerge 180121

Synchronize mcuboot up to upstream commit
3f49b5abf38659c22b6b73f5fe289de2e395263e

### CODE REVIEW

**Comment by hakonfam** [comment]
You need this patch:

```
diff --git a/zephyr/module.yml b/zephyr/module.yml
index c4293e3..7850f8b 100644
--- a/zephyr/module.yml
+++ b/zephyr/module.yml
@@ -1,4 +1,2 @@
 samples:
   - boot/zephyr
-build:
-  cmake: ./boot/bootutil/zephyr
```

**Comment by tejlmand** [comment]
> @tejlmand I'm not sure if this is the best solution for running the new `boot/bootutil/zephyr/CMakeLists.txt`, do you have any ideas?

what is the purpose of running the `bootutil/zephyr` inside nrf instead of running it automatically as a Zephyr module ?

**Comment by jfischer-no** [comment]
> > @tejlmand I'm not sure if this is the best solution for running the new `boot/bootutil/zephyr/CMakeLists.txt`, do you have any ideas?
> 
> what is the purpose of running the `bootutil/zephyr` inside nrf instead of running it automatically as a Zephyr module ?

@tejlmand [This](https://github.com/nrfconnect/sdk-mcuboot/blob/master/zephyr/CMakeLists.txt) was added long time ago, what let MCUboot module defaults _cmake_ to _extra build system logic_ in NCS, now it does not work with the upstream [changes](https://github.com/zephyrproject-rtos/mcuboot/commit/f573b392ec4ced1fc1daa267a7ad9111e08fdb4f#diff-27d260b3de385946dc5c56da8181a3a9d4f5897cfab9df6dc2f5bb56bb0bbd6fR4). What is the best way to solve it?

**Comment by tejlmand** [comment]
> @tejlmand [This](https://github.com/nrfconnect/sdk-mcuboot/blob/master/zephyr/CMakeLists.txt) was added long time ago, what let MCUboot module defaults _cmake_ to _extra build system logic_ in NCS, now it does not work with the upstream [changes](https://github.com/zephyrproject-rtos/mcuboot/commit/f573b392ec4ced1fc1daa267a7ad9111e08fdb4f#diff-27d260b3de385946dc5c56da8181a3a9d4f5897cfab9df6dc2f5bb56bb0bbd6fR4). What is the best way to solve it?

I see the problem. I will send a fix for this

**Comment by nvlsianpu** [comment]
^^ @tejlmand I this require to much efforts, can be done after upmerge as Håkon's patch works well.

**Comment by tejlmand** [comment]
> ^^ @tejlmand I this require to much efforts, can be done after upmerge as Håkon's patch works well.

The biggest challenge was to get the kids to bed :laughing: 

Please find two PRs here:
https://github.com/jfischer-no/sdk-nrf/pull/1
https://github.com/jfischer-no/sdk-mcuboot/pull/1

This uses the principle from https://github.com/zephyrproject-rtos/zephyr/pull/30904 and handle the glue code in `sdk-nrf` now, which means two file has been deleted in this repo, and the Kconfig has been moved the `sdk-nrf` :smile: 
You can cherrypick the commits onto the upmerge PRs', but for `sdk-mcuboot` PR you may also consider to do a revert of `ecbaa04e9ec0ca3f194e6a6de68a9c5ea1d64835` and then reapply while squashing the fix into that commit.
Pick the choice you like the most.

**Comment by jfischer-no** [comment]
> This uses the principle from [zephyrproject-rtos/zephyr#30904](https://github.com/zephyrproject-rtos/zephyr/pull/30904) and handle the glue code in `sdk-nrf` now, which means two file has been deleted in this repo, and the Kconfig has been moved the `sdk-nrf` smile
> You can cherrypick the commits onto the upmerge PRs', but for `sdk-mcuboot` PR you may also consider to do a revert of `ecbaa04e9ec0ca3f194e6a6de68a9c5ea1d64835` and then reapply while squashing the fix into that commit.
> Pick the choice you like the most.

Thank you @tejlmand, reverting and squashing did not work easy because of conflicts, I placed your commit at the top for now.

**Comment by tejlmand** [comment]
> Thank you @tejlmand, reverting and squashing did not work easy because of conflicts, I placed your commit at the top for now.

Not sure how you did it, but worked like a charm here, and we got even rid of this commit ee8ab63  in addition, as the Kconfig code is now in sdk-nrf:
https://github.com/tejlmand/fw-nrfconnect-mcuboot/tree/upmerge/revert_and_squash

and the final out-come of those current upmerge, and my revert and squash are identical, but with two fewer NCS patches:
```
$ git fetch ncs pull/136/head
From https://github.com/nrfconnect/sdk-mcuboot
 * branch            refs/pull/136/head -> FETCH_HEAD
$ git diff tejlmand-ncs/upmerge/revert_and_squash  FETCH_HEAD

**Comment by jfischer-no** [comment]
> Not sure how you did it, but worked like a charm here (edit: that is: _no conflicts_), and we got even rid of this commit [ee8ab63](https://github.com/nrfconnect/sdk-mcuboot/commit/ee8ab639004945282c129e66504727ff32ed7e89) in addition, as the Kconfig code is now in sdk-nrf:
> https://github.com/tejlmand/fw-nrfconnect-mcuboot/tree/upmerge/revert_and_squash

Yes have fixed it now, I overlooked commit ee8ab63, that was my conflict.

**Review by nvlsianpu — APPROVED** [review]

**Review by de-nordic — APPROVED** [review]
Looks OK

**Comment by nvlsianpu** [comment]
https://github.com/nrfconnect/sdk-mcuboot/pull/141 removes special treatment of upmerge PRs (these with [nrf mergeup] sauce tag). So compliance check can't pass on the upmerge anymore.

**Review by carlescufi — APPROVED** [review]

**Pull request merged**
